yatube/about/urls.py
from django.urls import path

from .views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        AboutTechView.as_view(),
        name='tech'
    )
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('group/<slug:slug>/', views.GroupView.as_view(), name='group_list'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('posts/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('posts/<post_id>/edit/', views.PostEditView.as_view(), name='update_post'),
    path('posts/<post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_id>/comment/', views.CommentView.as_view(), name='add_comment'),
    path('follow/', views.FollowIndexView.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/confirm/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change_form/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    )
]

yatube/yatube/urls.py
from django.urls import include

from yatube import settings

from django.conf.urls.static import static
from core.views import page_not_found

"""yatube URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the includes() function: from django.urls import includes, path
    2. Add a URL to urlpatterns:  path('blog/', includes('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve 


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
] 

urlpatterns += static(
        settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT
    )

handler404 = page_not_found
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

yatube/templates/includes/footer.html
<footer id="footer" class="border-top text-center py-3">
  <p>©
  Copyright 
  {{ year }}
  <span style="color: red">Ya</span>AslanDzen
  </p>
</footer>

yatube/templates/includes/header.html
{% load static %}

  <nav class="navbar navbar-expand-md bg-lightskyblue navbar-light" style="background-color: lightskyblue">
    <div class="container-fluid ">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>AslanDzen
      </a>
        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
      <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}">About Author</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}">Technologies</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">New Post</a>
        </li>
        <li class="nav-item">
        <a class="nav-link {% if view_name == 'users:password_change_form' %}active{% endif %}"
              href="{% url 'users:password_change_form' %}">Change Password</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Sign out</a>
        </li>
        <li>
          User: {{ user.username }}
        <li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Sign In</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Sign Up</a>
        </li>
        {% endif %}
        {% endwith %} 
      </ul>
      </div>
    </div>
  </nav>