yatube/about/urls.py
from django.urls import path

from .views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        AboutTechView.as_view(),
        name='tech'
    )
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('group/<slug:slug>/', views.GroupView.as_view(), name='group_list'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('posts/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('posts/<post_id>/edit/', views.PostEditView.as_view(), name='update_post'),
    path('posts/<post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_id>/comment/', views.CommentView.as_view(), name='add_comment'),
    path('follow/', views.FollowIndexView.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.urls import include

from yatube import settings

from django.conf.urls.static import static
from core.views import page_not_found

"""yatube URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the includes() function: from django.urls import includes, path
    2. Add a URL to urlpatterns:  path('blog/', includes('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve 


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
] 

urlpatterns += static(
        settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT
    )

handler404 = page_not_found
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="Name")
    slug = models.SlugField(unique=True, verbose_name="Slug")
    description = models.TextField(verbose_name="Description")

    def __str__(self):
        return self.title

class Post(CreatedModel):
    text = models.TextField(verbose_name="Post Text",
                            help_text='This field is for the text of the post, '
                                      'it has no character limits.')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="posts",
                               verbose_name="Post Author")
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              related_name="posts",
                              blank=True,
                              null=True,
                              verbose_name="Group",
                              help_text='This is the field for selecting the post group, '
                                        'it is optional.'
                              )
    image = models.ImageField(verbose_name='Image',
                              upload_to='posts/',
                              blank=True,
                              help_text='This field is for adding photos.')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

class Comment(models.Model):
    post = models.ForeignKey(Post, verbose_name='Post Reference',
                             related_name='comments',
                             on_delete=models.CASCADE,
                             )
    author = models.ForeignKey(User, verbose_name='Author Reference',
                               related_name='comments',
                               on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Comment Text')
    created = models.DateTimeField('Creation Date',
                                   auto_now_add=True,
                                   db_index=True)
    likes = models.ManyToManyField(User, verbose_name="Likes",
                                   related_name='users',
                                   blank=True
                                   )

    def get_likes(self):
        return self.likes.prefetch_related().count()

    def __str__(self):
        return f"{self.text}, likes: {self.likes}"

class Follow(models.Model):
    user = models.ForeignKey(User, verbose_name='Follower',
                             related_name='follower',
                             on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Following',
                               related_name='following',
                               on_delete=models.CASCADE)

    def __str__(self):
        return f'Follower: {self.user}, Following: {self.author}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'], name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms

from enums import PostModelEnum
from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (PostModelEnum.TEXT.value, PostModelEnum.GROUP.value, PostModelEnum.IMAGE.value)
        help_texts = {
            'text': 'This field is for the text of the post, '
                    'it has no character limits.',
            'group': 'This is the field for selecting the post group, '
                     'it is optional.'
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (PostModelEnum.TEXT.value,)
        widgets = {
            "text": forms.TextInput(attrs={"id": "chat-message-input"})
        }

yatube/posts/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from enums import HtmlPathEnum
from .models import Group, Post, User, Follow
from .forms import PostForm, CommentForm
from .utils import get_users


class IndexView(ListView):
    model = Post
    template_name = HtmlPathEnum.INDEX_PAGE.value
    paginate_by = 5


class GroupView(ListView):
    template_name = HtmlPathEnum.GROUP_PAGE.value
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        return context

    def get_queryset(self, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        posts = group.posts.all()
        return posts


class ProfileView(ListView):
    model = Post
    template_name = HtmlPathEnum.PROFILE_PAGE.value
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(User,
                                   username=self.kwargs.get('username'))
        posts = author.posts.all()
        context['author'] = author
        context['page_obj'] = posts
        context['count_posts'] = posts.count()
        context['following'] = False
        if self.request.user.is_authenticated:
            if Follow.objects.filter(user=self.request.user,
                                     author=author).exists():
                context['following'] = True
        return context


class PostDetailView(DetailView):
    template_name = HtmlPathEnum.POST_DETAIL_PAGE.value

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(Post, id=self.kwargs.get('post_id'))
        comments = post.comments.all()
        form = CommentForm(self.request.POST or None)
        context['form'] = form
        context['post'] = post
        context['page_obj'] = comments
        return context

    def get_object(self, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('post_id'))
        return post


class PostCreateView(CreateView, LoginRequiredMixin):
    model = Post
    template_name = HtmlPathEnum.POST_CREATE_EDIT_PAGE.value
    form_class = PostForm

    def get_success_url(self):
        return reverse('posts:profile', args=[self.request.user])

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)


class PostEditView(UpdateView, LoginRequiredMixin):
    model = Post
    template_name = HtmlPathEnum.POST_CREATE_EDIT_PAGE.value
    pk_url_kwarg = 'post_id'
    fields = '__all__'

    def get_success_url(self):
        return reverse('posts:profile', args=[self.request.user])


class PostDeleteView(DeleteView, LoginRequiredMixin):
    model = Post
    pk_url_kwarg = 'post_id'

    def get_success_url(self):
        success_url = str(reverse_lazy('posts:index'))
        return success_url

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CommentView(CreateView, LoginRequiredMixin):
    model = Post
    form_class = CommentForm

    def get_success_url(self):
        success_url = str(reverse_lazy('posts:post_detail',
                                       args=[self.kwargs.get('post_id')]))
        return success_url

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post_id = self.kwargs.get('post_id')
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)


class FollowIndexView(ListView, LoginRequiredMixin):
    model = Post
    template_name = HtmlPathEnum.FOLLOW_PAGE.value
    paginate_by = 10

    def get_queryset(self):
        follower = get_object_or_404(User, username=self.request.user)
        following_list = Follow.objects.filter(user=follower).values('author')
        posts = Post.objects.filter(author_id__in=following_list)
        return posts


@login_required
def profile_follow(request, username):
    follower, following = get_users(request, username)
    if request.user != following:
        Follow.objects.get_or_create(user=follower,
                                     author=following)
    return redirect(reverse('posts:profile',
                            args=[username]))


@login_required
def profile_unfollow(request, username):
    follower, following = get_users(request, username)
    follow_obj = Follow.objects.filter(user=follower,
                                       author=following)
    follow_obj.delete()
    return redirect(reverse('posts:profile',
                            args=[username]))

yatube/templates/posts/create_post.html
{% extends "base.html" %} {% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %} Edit post {% else %} New Post {% endif %}
      </div>
      <div class="card-body">
        {% load user_filters %} {% if form.errors %} {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">{{ error|escape }}</div>
        {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
        <div class="alert alert-danger">{{ error|escape }}</div>
        {% endfor %} {% endif %}
        <form
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
           {% for field in form %}
          <div class="form-group row my-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }} {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>
              {{ field|addclass:'form-control' }} {% if field.help_text %}
              <small
                id="{{ field.id_for_label }}-help"
                class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
          <div class="text-center">
            <button id="submit-button" type="submit" class="btn btn-primary">
              {% if is_edit %} Save {% else %} Add {% endif %}
            </button>
          </div>
        </form>
      </div>
      <!-- card body -->
    </div>
    <!-- card -->
  </div>
  <!-- col -->
</div>
<!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load cache %}
{% block content %}
<div class="col-md-8 p-5">
  <div class="container">
    <h1 style>User Subscription Posts</h1>
    {% include 'posts/includes/switcher.html' %}
    {% cache 20 index_page %}
    {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">All Group Posts</a>
    <br>
    {% endif %}
    <a href="{% url 'posts:post_detail' post.id %}">More...</a>
        <hr>
    {% endfor %}
  {%  endcache %}

  </div>
</div>

{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}
<div class="col-md-8 p-5">
  <div class="container">
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
      <hr>
      {% endfor %}
  </div>
</div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block content %}

<div class="col-md-8 p-5">
  <div class="container">
    <h1 class="last_update_text" style>Last updates</h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
    {% if post.group %}
    <a type="button" id="btn_main_page" class="btn btn-outline-primary" href="{% url 'posts:group_list' post.group.slug %}">All Articles of Group</a>
    <a type="button" id="btn_main_page" class="btn btn-outline-primary" href="{% url 'posts:post_detail' post.id %}">More...</a>
    <br/>
    {% endif %}
    {% if post.author == request.user %}
        <li class="post_opportunities">
    <a type="button" id="btn_main_page"  class="btn btn-outline-success" href="{% url 'posts:update_post' post.id %}">Edit Post</a>
    <a type="button" id="btn_main_page"  class="btn btn-outline-danger" href="{% url 'posts:post_delete' post.id %}">Delete Post</a>
        </li>
        <style>
  .post_opportunities {
    list-style-type: none; /* Убираем маркеры */
   }
        </style>
    {% endif %}
    <hr>
    {% endfor %}
  </div>
</div>

{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load static %}

{% block content %}
    <div class="container py-5">
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Publication Date: {{ post.pub_date|date:"d E Y" }}
                    </li>
                    {% if post.group %}
                        <li class="list-group-item">
                        Group:<a type="button" id="btn_main_page" class="btn btn-outline-primary"
                                  href="{% url 'posts:group_list' post.group.slug %}">{{ post.group }}</a>
                    {% endif %}
                    </li>
                    <li class="list-group-item">
                        Author: <a class="btn btn-outline-primary"
                                  href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Total of author posts: {{ count_posts }}
                    </li>
                    <li class="list-group-item">
                        </a>
                    </li>
                </ul>
            </aside>
            <article id="text-detail-post" class="col-12 col-md-9">
                {% include 'posts/includes/post_with_photo.html' %}
            </article>
        </div>
    </div>

    {% if user.is_authenticated %}
        <div class="card my-4 text-center" style="width:80%; right: auto; left:10%">
            <h5 class="card-header">Add comment:</h5>
            <div class="card-body">
                {% csrf_token %}
                <div class="form-floating">
                    <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                    </div>
                </div>
                <input id="chat-message-submit" class="btn btn-primary" type="button" value="Send">
                {{ post_id|json_script:"post_id" }}
            </div>
        </div>
    {% endif %}
    {% for comment in page_obj %}
        <div class="container_comment">
            <div class="comment__container opened" id="first-comment">
                <div class="comment__card">
                    <h3 class="comment__title flex_element">{{ comment.author.username }}</h3>
                    <small><p id="date" style="font-size: 10px;" class="flex_element">{{ created }}</p></small>
                    <p>
                        {{ comment.text }}
                    </p>
                    <div class="comment__card-footer">
                        <div>
                            <img src="{% static 'img/like.png' %}" class="likes" type="button"
                                 id="{{ comment.id|safe }}">
                            <input class="like_counter" value="{{ comment.get_likes }}" id="{{ comment.id|safe }}"
                                   type="button">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <script>
    let reconnectAttempts = 0;
    const maxReconnectAttempts = 5;  // You can adjust the maximum number of reconnection attempts

    function connectWebSocket() {
        const post_id = JSON.parse(document.getElementById('post_id').textContent);
        const ws_scheme = window.location.protocol === "https:" ? "wss://" : "ws://";
        window.chatSocket = new WebSocket(
            ws_scheme
            + window.location.host
            + ":8001"
            + '/ws/posts/'
            + '{{ post.id }}'
            + '/'
        );

        window.chatSocket.onmessage = function (e) {
            const today = new Date();
            const data = JSON.parse(e.data);

            if (data.type === 'chat_message') {
                const parentNodeMain = document.querySelector('main')

                const containerDiv = parentNodeMain.appendChild(document.createElement('div'))
                containerDiv.classList.add('container_comment')

                const commentContainerInternal = containerDiv.appendChild(document.createElement('div'))
                commentContainerInternal.classList.add('comment__container')
                commentContainerInternal.classList.add('opened')

                const commentCard = commentContainerInternal.appendChild(document.createElement('div'))
                commentCard.classList.add('comment__card')

                const userNameDiv = commentCard.appendChild(document.createElement('h3'))
                userNameDiv.classList.add('comment__title')
                userNameDiv.classList.add('flex_element')
                userNameDiv.textContent = data.username

                const smallBlockWithTextAndDate = commentCard.appendChild(document.createElement('small'))
                const dateElement = smallBlockWithTextAndDate.appendChild(document.createElement('p'))
                dateElement.classList.add('flex_element')
                dateElement.setAttribute('id', 'date')
                dateElement.setAttribute('style', 'font-size:10px;')
                dateElement.textContent = `${today.getFullYear().toString().slice(2)}-${today.getMonth() + 1}-${today.getUTCDate()},
                                       ${today.getHours() - 1}:${today.getMinutes()}`;

                const pElementTextContent = commentCard.appendChild(document.createElement('p'))
                pElementTextContent.textContent = data.message

                const commentFooterDiv = commentCard.appendChild(document.createElement('div'))
                commentFooterDiv.classList.add('comment__card-footer')

                const internalDivLike = commentFooterDiv.appendChild(document.createElement('div'))
                const imgElem = internalDivLike.appendChild(document.createElement('img'))
                imgElem.setAttribute('src', "{% static 'img/like.png' %}");
                imgElem.setAttribute('class', 'likes')
                imgElem.setAttribute('type', 'button')
                imgElem.style.width = '25px;'
                imgElem.style.height = '25px;'

                const buttonLike = internalDivLike.appendChild(document.createElement('input'))
                buttonLike.setAttribute('class', 'like_counter')
                buttonLike.setAttribute('type', 'button')

                imgElem.setAttribute('id', `${data.comment_id}`);
                buttonLike.setAttribute('id', `${data.comment_id}`);
                buttonLike.value = "0"

            } else {
                const likeIndicate = document.querySelector(`input[id="${data.comment_id}"]`)
                likeIndicate.value = data.likes_count
            }
        };

        chatSocket.onclose = function (e) {
            if (reconnectAttempts < maxReconnectAttempts) {
                setTimeout(function () {
                    reconnectAttempts++;
                    connectWebSocket();  // Attempt to reconnect
                }, 2000);  // 2000 milliseconds (adjust as needed)
            } else {
                console.error('Max reconnect attempts reached. Chat socket closed unexpectedly', e);
            }
        }

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {
                document.querySelector('#chat-message-submit').click();
            }
        };
    }
        function addComment() {
            document.querySelector('#chat-message-submit').addEventListener('click', function (e) {
                    const messageInputDom = document.querySelector('#chat-message-input');
                    const message = messageInputDom.value;
                    if (messageInputDom.value !== "") {
                        window.chatSocket.send(JSON.stringify({
                            'message': message,
                            'username': "{{ request.user.username }}",
                            'room': "{{ post.id }}"
                        }));
                        messageInputDom.value = '';
                    }
                }
            )
        }

        addComment()

        function addSocketLike(id) {
            window.chatSocket.send(JSON.stringify({
                'comment_id': id,
                'username': "{{ request.user.username }}",
            }));
        }

        document.addEventListener('click', function (event) {
            if (event.target.classList.contains('likes')) {
                addSocketLike(event.target.id)
            }
        });
    connectWebSocket();

    </script>
    {% else %}
    {% endif %}

    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">
    <h1>All posts by user {{ author.get_full_name }}</h1>
    <h3>Total posts: {{ count_posts }}</h3>
    {% if request.user != author %}
        {% if following %}
        <a id="follow_btn" class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button">
          Unfollow
        </a>
        {% elif not following %}
          <a id="follow_btn" class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button">
            Follow
          </a>
        {% else %}
      <p>Button should be here</p>
   {% endif %}
  {% endif %}
  </div>
  <hr>
    <ul class="list-group list-group-flush">
  {% for post in page_obj %}
  {% if post.group %}
      <li id="posts_list" class="list-group-item border-0 ">
  Group: <a class="btn btn-light" href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.slug|upper }}</a>
  {% endif %}
            </li>
      <li class="list-group-item">
          Publication Date: {{ post.pub_date|date:"d E Y" }}
      </li>
  {% include 'posts/includes/post_with_photo.html' %}
  <hr>
  {% endfor %}
</ul>
{% include 'posts/includes/paginator.html' %}
{% endblock %}
</div>