yatube/about/urls.py
from django.urls import path

from .views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        AboutTechView.as_view(),
        name='tech'
    )
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/confirm/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change_form/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    )
]

yatube/yatube/urls.py
from django.urls import include

from yatube import settings

from django.conf.urls.static import static
from core.views import page_not_found

"""yatube URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the includes() function: from django.urls import includes, path
    2. Add a URL to urlpatterns:  path('blog/', includes('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve 


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
] 

urlpatterns += static(
        settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT
    )

handler404 = page_not_found
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from enums import UserModelEnum

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (UserModelEnum.FIRST_NAME.value, UserModelEnum.LAST_NAME.value,
                  UserModelEnum.USERNAME.value, UserModelEnum.EMAIL.value)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}You are sign out!{% endblock %}
{% block content %}
{% with card_header='Sign out' card_body='You are logged out of your account' %}
{% include 'users/includes/card.html' %}
{% endwith %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Sign In{% endblock %}
{% block content %}
{% load user_filters %}
  {% with card_header='Authorization' %}
    {% include 'users/includes/header_card.html' %}
      {% endwith %}
  {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
  {% endif %}

  <form method="post"
    {% if action_url %}
      action="{% url action_url %}"
    {% endif %}>
  {% csrf_token %}

  {% for field in form %}
    <div class="form-group row my-3"
      {% if field.field.required %}
        aria-required="true"
      {% else %}
        aria-required="false"
      {% endif %}>
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>
          {% endif %}
      </label>
      <div>
      {{ field|addclass:'form-control' }}
        {% if field.help_text %}
          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
    </div>
  {% endfor %}
  <div class="text-center">
    <button type="submit" class="btn btn-primary">
      Sign In
    </button>
    <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
      Forgot password?
    </a>
  </div>
  </form>
    {% include 'users/includes/body_card.html' %}
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Change password{% endblock %}
{% block content %}
  {% with card_header='Change password' card_body='Your password has been saved!' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Change password{% endblock %}

{% block content %}
  {% with card_header='Change password' %}
    {% include 'users/includes/header_card.html' %}
      {% endwith %}
      {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group row my-3 p-3">
      <label for="id_old_password">
        Old password
        <span class="required text-danger">*</span>
      </label>
      <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
    </div>
    <div class="form-group row my-3 p-3">
      <label for="id_new_password1">
        New Password
        <span class="required text-danger">*</span>
      </label>
      <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
        <small id="id_new_password1-help" class="form-text text-muted">
          <ul><li>Password is not secure.</li><li>Password must consist minimum with 8 symbols.</li><li>Your password cant consist with only numbers.</li></ul>
        </small>
    </div>
    <div class="form-group row my-3 p-3">
      <label for="id_new_password2">
        Confirm new password
        <span class="required text-danger">*</span>
      </label>
      <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
    </div>
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        Change password
      </button>
    </div>
      </form>
    {% include 'users/includes/body_card.html' %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Password recovery completed{% endblock %}
{% block content %}
{% with card_header='Password recovery completed' card_body='Password has been saved!' %}
{% include 'users/includes/card.html' %}
    <div>
        <a href="{% url 'users:login' %}">Sign in</a>
    </div>
{% endwith %}

{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Confirm password{% endblock %}
{% block content %}
    {% with card_header='Password recovery' %}
    {% include 'users/includes/header_card.html' %}
    {% endwith %}
    <form method="post">
    {% csrf_token %}
    <input  type="hidden" name="next" value="{{ next }}">
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary btn-block">Reset</button>
    </form>
    {% include 'users/includes/header_card.html' %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Password recovery{% endblock %}
{% block content %}
    {% with card_header='Letter has been sent' card_body='Check your email' %}
    {% include 'users/includes/card.html' %}
    {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Password Recovery{% endblock %}
{% block content %}
    {% with card_header='Select email address' %}
    {% include 'users/includes/header_card.html' %}
    {% endwith %}
<form method="post">
{% csrf_token %}
<div class="form-group row my-3 p-3">
  <label for="id_email">
    Email
  <span class="required text-danger">*</span>
  </label> 
  <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
</div>
<div class="col-md-6 offset-md-5">
<button type="submit" class="btn btn-primary">
  Recovery
  </button>
</div>
</form>
{% include 'users/includes/body_card.html' %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Sign up{% endblock %}
{% block content %}
{% with card_header='Sign up' %}
{% include 'users/includes/header_card.html' %}
  {% endwith %}
      {% load user_filters %}
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-primary">
              Sign up
            </button>
          </div>
        </form>
    {% include 'users/includes/body_card.html' %}
{% endblock %}